### ISSUE TITLE
数据库要自己手动添加么？

### ISSUE THREAD

**Issue by micln** [BNUACM/bnuoj-web-v3#1]
找不到sql之类的。。

**Comment by iloahz** [comment]
@micln try this: https://github.com/51isoft/bnuoj/blob/master/bnuoj-schema.sql

**Comment by micln** [comment]
阔以的~

不过问题又来了，登陆的时候显示success但还是未登陆状态。
cookie里的帐号和密码都是 deleted 。 数据库里已经有对应的信息了
这是啥子情况？

**Comment by iloahz** [comment]
Just took a look at the code:
https://github.com/BNUACM/bnuoj-web-v3/blob/develop/ajax/login.php#L24
So if you see the message "Success...", you should have passed the (username, password) check, however this line:
https://github.com/BNUACM/bnuoj-web-v3/blob/develop/ajax/login.php#L19
indicates there's an expire date for cookies, so I suppose you can double check if the variable `$exp` is set correctly(and also your browser's time).

I am not very familiar with the logic, try contacting @51isoft for better help.

**Comment by 51isoft** [comment]
不太确定啥情况，您能用工具看一下具体的XHR请求

**Comment by micln** [comment]
我换了个服务器，本地机也是多机测试。

出现了注册时success但数据库没有信息，手动导入后登陆出现同上错误。

**Comment by 51isoft** [comment]
您用开发者工具调试一下吧

**Comment by oraclexbw** [comment]
终于见到当年刷oj的源代码了，我大一的时候还困惑这个网站是怎么做的
