### ISSUE TITLE
请问怎么样才能实现UVA和UVALIVE的填入ID抓题？

### ISSUE THREAD

**Issue by quyunhua** [BNUACM/bnuoj-web-v3#32]
非常需要这个功能，请问能告诉我怎么解决吗？谢谢您了！

**Comment by crccw** [comment]
Please execute monitor/prepare_uva.php in command line

**Comment by quyunhua** [comment]
![default](https://cloud.githubusercontent.com/assets/14905569/10473309/99358d20-725c-11e5-8a8f-a7effeeba7bb.png)
请问命令行下运行显示这个，是正常的吗？

**Comment by quyunhua** [comment]
![default](https://cloud.githubusercontent.com/assets/14905569/10473381/47fbe8e0-725d-11e5-8cb0-21bae3b1d2f6.png)
运行中遇到错误了？请问这是什么原因啊

**Comment by quyunhua** [comment]
我是这里down下来的全新的代码，而且没有做任何改动，不知道具体什么原因？
