### ISSUE TITLE
execute monitor/prepare_uva.php in command line wrong?

### ISSUE THREAD

**Issue by quyunhua** [BNUACM/bnuoj-web-v3#35]
![default](https://cloud.githubusercontent.com/assets/14905569/10477967/e0fc14fa-728c-11e5-8cc4-0f056f7398c6.png)
今天从这里download的qu全新代码，而且没有做任何改动，还是报错，请问该怎么检查错误啊？

**Comment by crccw** [comment]
Not reproductive

**Comment by 51isoft** [comment]
Please try to debug yourself, since their might be connectivity issues on your side. And GitHub is NOT a customer service platform, which, we actually don't provide.
