### ISSUE TITLE
How to set recent contest

### ISSUE THREAD

**Issue by quyunhua** [BNUACM/bnuoj-web-v3#36]
请问最近比赛的信息具体是如何更新，能给个具体设置方法吗？
谢谢您！

**Comment by crccw** [comment]
Recent contest is read from external/contests.json

**Comment by quyunhua** [comment]
请问external/contests.json这个文件的数据怎么更新啊

**Comment by crccw** [comment]
We use http://contests.acmicpc.info/contests.json as our source
You can use any source as long as the format meets

**Comment by quyunhua** [comment]
我就是不太清楚具体要怎么用这个源？请问有参考文档吗？

**Comment by 51isoft** [comment]
You can write a cron job yourself.

**Comment by quyunhua** [comment]
就是不太明白怎么写？
external/contests.json 就是这个文件如何定时更新成http://contests.acmicpc.info/contests.json，不太明白
