### ISSUE TITLE
您好！我用admin_index.php里面的Problem Crawler的Crawl problems/contests in range

### ISSUE THREAD

**Issue by quyunhua** [BNUACM/bnuoj-web-v3#37]
1、能抓一部分的uva的题目，但是题目的pdf都不能下载到我的服务器
![1](https://cloud.githubusercontent.com/assets/14905569/10595692/b51b45d8-770d-11e5-9dcf-847bd613c23d.png)
![2](https://cloud.githubusercontent.com/assets/14905569/10595693/b520e95c-770d-11e5-8ca7-9f867e606f16.png)
2、抓100-103没问题，抓10000-10003缺显示没有这个题目？
3、还有我用monitor下的update_all.php别的题库都能抓下来，就是uva和uvalive抓不下来。
请问我该如何查看这些错误啊？
谢谢！

**Comment by quyunhua** [comment]
![2](https://cloud.githubusercontent.com/assets/14905569/10595699/c9dc62f4-770d-11e5-9864-4641fbe7db20.png)

**Comment by 51isoft** [comment]
Please check your connectivity, your last issue clearly indicated that you didn't fetch all needed urls.
And please at least read the code a little bit by yourself, this is an open source project using GPLv3 license, we DO NOT provide detailed customer service at this level.
